# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.cache/wt [current_project]
set_property parent.project_path C:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {{c:/cosas/eseca_m2/soc/soc_project/vhdl/ekhi/soc_fir 2020-12-05/soc_fir/soc_fir.srcs/sources_1/new}} [current_project]
update_ip_catalog
set_property ip_output_repo c:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files C:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.srcs/sources_1/bd/design_1/ip/design_1_vio_0_0_1/design_1_vio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.srcs/sources_1/bd/design_1/ip/design_1_vio_0_0_1/design_1_vio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.srcs/constrs_1/new/basys3_master.xdc
set_property used_in_implementation false [get_files C:/cosas/eseca_M2/SoC/SoC_project/FIR_filter_reloadable/FIR_filter_reloadable/FIR_filter_reloadable.srcs/constrs_1/new/basys3_master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
